<?php
session_start();
$usr = "";
$usrlog = "Login";
$loglink = "login.php";
$wel = "";
$bp = "";
if (isset($_SESSION['userName'])) {
	$usr = $_SESSION['userName'];
	$usrlog = $_SESSION['usrlog'];
	$loglink = $_SESSION['loglink'];
	$wel = "Welcome ";
} else {
	header("Location: Login.php");
}


echo "\n"; 
echo "<!doctype html>\n"; 
echo "<hmtl>\n"; 
echo "<head>\n"; 
echo "<meta charset=\"utf-8\">\n"; 
echo "<title>Booking</title>\n"; 
echo "<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "<link href=\"css/form.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "<link href=\"css/booking.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "\n"; 
echo "\n"; 
echo "<script language=\"javascript\"> \n"; 
echo "<!-- \n"; 
echo "function setOptions(chosen) \n"; 
echo "{ \n"; 
echo "var selbox = document.myform.opttwo; \n"; 
echo "selbox.options.length = 0; \n"; 
echo "if (chosen == \" \") { \n"; 
echo "selbox.options[selbox.options.length] = new Option('Select above first',' '); \n"; 
echo "\n"; 
echo "} \n"; 
echo "if (chosen == \"Hatchback\") { \n"; 
echo "selbox.options[selbox.options.length] = new Option('Sparkling Gold'); \n"; 
echo "selbox.options[selbox.options.length] = new Option('Deep Impact Blue'); \n"; 
echo "selbox.options[selbox.options.length] = new Option('Smoke Gray'); \n"; 
echo "selbox.options[selbox.options.length] = new Option('Tuxedo Black'); \n"; 
echo "selbox.options[selbox.options.length] = new Option('Ruby Red'); \n"; 
echo "selbox.options[selbox.options.length] = new Option('Ingot Silver'); \n"; 
echo "selbox.options[selbox.options.length] = new Option('Oxford White'); \n"; 
echo "} \n"; 
echo "if (chosen == \"SUV\") { \n"; 
echo "selbox.options[selbox.options.length] = new Option('Chill Metallic'); \n"; 
echo "selbox.options[selbox.options.length] = new Option('Kinetic Blue');  \n"; 
echo "selbox.options[selbox.options.length] = new Option('Smoke Gray'); \n"; 
echo "selbox.options[selbox.options.length] = new Option('Panther Black'); \n"; 
echo "selbox.options[selbox.options.length] = new Option('Mars Red'); \n"; 
echo "selbox.options[selbox.options.length] = new Option('Moondust Silver'); \n"; 
echo "selbox.options[selbox.options.length] = new Option('Diamond White'); \n"; 
echo "} \n"; 
echo "\n"; 
echo "} \n"; 
echo "--> \n"; 
echo "</script> \n"; 
echo "\n"; 
echo "\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body>\n"; 
echo "<div class=\"log\" ><a href=\"$loglink\">$usrlog</a></div>\n";  
echo "<div class=\"log\"><label>$wel $usr</label></div>";
echo "<div class=\"head\" ><img src=\"images/logo.png\" width=\"500\" height=\"110\" alt=\"\"/></div>\n"; 
echo "<hr class=\"hline\" color=\"#000000\" />\n"; 
echo "\n"; 
echo "<div>\n"; 
echo "	<ul class=\"mainNav\">\n"; 
echo "    <li><a  href=\"index.php\">Home</a></li>\n"; 
echo "    <li class=\"drop\"><a href=\"models_hatch.php\">Models</a>\n"; 
echo "    	<ul class=\"SubMenu\">\n"; 
echo "        	<li><a href=\"models_hatch.php\">Hatchback</a></li>\n"; 
echo "           <li><a href=\"models_suv.php\">SUV</a></li>   \n"; 
echo "        </ul>\n"; 
echo "    </li>\n"; 
echo "    <li><a class=\"active\" href=\"booking.php\">Booking</a></li>\n"; 
echo "    <li><a href=\"service.php\">Service</a></li>\n"; 
echo "    <li><a href=\"about.php\">About</a></li>\n"; 
echo "    <li><a href=\"contact.php\">Contact</a></li></ul>\n"; 
echo "</div>\n"; 
echo "<hr class=\"hline\" color=\"#000000\" />\n"; 
echo "<form name=\"myform\" action=\"booking_price_val.php\" method=\"POST\" >\n"; 
echo "<div class=\"form\">\n"; 
echo "<table>\n"; 
echo "    	<tr><td>Model</td><td><select name=\"optone\"  id=\"mdl\" autofocus required onclick=\"setOptions(document.myform.optone.options[document.myform.optone.selectedIndex].value);\" >\n"; 
echo "    	  <option value=\"Hatchback\">Hatchback</option>\n"; 
echo "    	  <option value=\"SUV\">SUV</option>\n"; 
echo "      </select></td></tr>	  \n"; 
echo "      <tr><td>Color</td><td><select  name=\"opttwo\" size=\"1\" size=\"1\" autofocus required  >\n"; 
echo "	  <option value=\" \" selected=\"selected\">Select above first</option> \n"; 
echo "    	  \n"; 
echo "	</select></td></tr>\n"; 
echo "    <tr><td>Varient</td><td><select name=\"varient\" autofocus required >\n"; 
echo "    	  <option value=\"Base --- Petrol\">Base --- Petrol</option>\n"; 
echo "    	  <option value=\"Mid --- Petrol\">Mid --- Petrol</option>\n"; 
echo "    	  <option value=\"Top --- Petrol\">Top --- Petrol</option>\n"; 
echo "          <option value=\"Base --- Diesel\">Base --- Diesel</option>\n"; 
echo "          <option value=\"Mid --- Diesel\">Mid --- Diesel</option>\n"; 
echo "          <option value=\"Top --- Diesel\">Top --- Diesel</option>\n"; 
echo "	</select></td>\n";  
echo "    <tr><td><input name=\"submit\" type=\"submit\" value=\"Show Price\"/></td></tr>\n"; 
echo "    \n"; 
echo "    \n"; 
echo "    \n"; 
echo "</table>\n"; 
echo "</div>\n"; 
echo "</form>\n"; 
echo "\n"; 
echo "</div>\n"; 
echo "<div class=\"carArrange\">\n"; 
echo "<img src=\"images/car.jpg\" alt=\"car\" />\n"; 
echo "</div>\n";
echo "\n"; 
echo "</body>\n"; 
echo "</html>\n"; 
echo "\n";
?>