<?php
include 'php/log_info.php';
echo "\n"; 
echo "<!doctype html>\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "<meta charset=\"utf-8\">\n"; 
echo "<title>Hatch</title>\n"; 
echo "<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "<link href=\"css/models.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "<script src=\"js/frontScroll.js\"></script>\n"; 
echo "<script src=\"js/hatchExt.js\"></script>\n"; 
echo "<script src=\"js/color.js\"></script>\n"; 
echo "<script src=\"js/smoothScroll.js\"></script>\n"; 
echo "<script src=\"js/hatchint.js\"></script>\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body>\n"; 
echo "\n"; 
echo "<div class=\"log\" ><a href=\"$loglink\">$usrlog</a></div>\n"; 
echo "<div class=\"log\"><label>$wel $usr</label></div>";
echo "<div class=\"head\" ><img src=\"images/logo.png\" width=\"500\" height=\"110\" alt=\"\"/></div>\n"; 
echo "<hr class=\"hline\" color=\"#000000\" />\n"; 
echo "\n"; 
echo "<div>\n"; 
echo "	<ul class=\"mainNav\">\n"; 
echo "    <li><a href=\"index.php\">Home</a></li>\n"; 
echo "    <li class=\"drop\"><a class=\"active\" href=\"models_hatch.php\">Models</a>\n"; 
echo "    	<ul class=\"SubMenu\">\n"; 
echo "        	<li><a class=\"active\" href=\"models_hatch.php\">Hatchback</a></li>\n"; 
echo "           <li><a href=\"models_suv.php\">SUV</a></li>   \n"; 
echo "        </ul>\n"; 
echo "    </li>\n"; 
echo "    <li><a href=\"booking.php\">Booking</a></li>\n"; 
echo "    <li><a href=\"service.php\">Service</a></li>\n"; 
echo "    <li><a href=\"about.php\">About</a></li>\n"; 
echo "    <li><a href=\"contact.php\">Contact</a></li></ul>\n"; 
echo "</div>\n"; 
echo "<hr class=\"hline\" color=\"#000000\" />\n"; 
echo "\n"; 
echo "<section id=\"exterior\" >\n"; 
echo "<h2> Exterior 360 Degree View</h2>\n"; 
echo "<img id=\"myImage\" src=\"images/hatch/1 (1).jpg\"  alt=\"\"/>\n"; 
echo "<input type=\"button\" id=\"trans\" value=\"&#10097\" onClick=\"displayNextImage()\">\n"; 
echo "<input type=\"button\" id=\"trans2\" value=\"&#10096\" onClick=\"displayPreviousImage()\" name=\"img\">\n"; 
echo "</section>\n"; 
echo "\n"; 
echo "<section id=\"interior\">\n"; 
echo "<h2 > Interior 360 Degree View</h2>\n"; 
echo "<img id=\"interiorview\" src=\"images/hatch/HatchInt/1 (1).jpg\"  alt=\"int\" width=\"100%\"/>\n"; 
echo "<input type=\"button\" id=\"transInt\" value=\"&#10097\" onClick=\"displayNextImageHatInt()\">\n"; 
echo "<input type=\"button\" id=\"transInt2\" value=\"&#10096\" onClick=\"displayPreviousImageHatInt()\" name=\"img\">\n"; 
echo "</section>\n"; 
echo "\n"; 
echo "\n"; 
echo "<section id=\"feature\">\n"; 
echo "<img src=\"images/hatch/features1.JPG\" width=\"100%\" />\n"; 
echo "</section>\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "<section id=\"colors\">\n"; 
echo "<h2>Colors</h2>\n"; 
echo "<table width=\"99%\">\n"; 
echo "<tr><td><div id=\"car\"><img src=\"images/hatch/colors/1 (2).jpg\" width=\"980\" height=\"390\" alt=\"\" id=\"colormdl\" />\n"; 
echo "<h3 id=\"demo\">Sparkling Gold</h3></div><br></td></tr>\n"; 
echo "    <tr><td><div id=\"colorChoose\" >\n"; 
echo "		<input type=\"image\" src=\"images/colorCode/orange.jpg\" alt=\"orange\"  onClick=\"clr1()\"/> \n"; 
echo "    	<input type=\"image\" src=\"images/colorCode/red.jpg\" alt=\"red\" onClick=\"clr2()\" /> \n"; 
echo "    	<input type=\"image\" src=\"images/colorCode/black.jpg\" alt=\"black\" onClick=\"clr3()\" /> \n"; 
echo "    	<input type=\"image\" src=\"images/colorCode/blue.jpg\" alt=\"blue\" onClick=\"clr4()\" /> \n"; 
echo "    	<input type=\"image\" src=\"images/colorCode/silver.jpg\" alt=\"silver\" onClick=\"clr5()\" /> \n"; 
echo "    	<input type=\"image\" src=\"images/colorCode/white.jpg\" alt=\"white\" onClick=\"clr6()\" /> \n"; 
echo "    	<input type=\"image\" src=\"images/colorCode/gray.jpg\" alt=\"gray\" onClick=\"clr7()\" /> \n"; 
echo "  	</div></td></tr>\n"; 
echo "  </table>\n"; 
echo "</section>\n"; 
echo "\n"; 
echo "\n"; 
echo "<nav id=\"footMenu\">\n"; 
echo "	<ul id=\"footeft\">\n"; 
echo "    	<li><a href=\"#exterior\">EXTERIOR</a></li>\n"; 
echo "    	<li><a href=\"#interior\">INTERIOR</a></li>\n"; 
echo "    	<li><a href=\"#feature\">FEATURE</a></li>\n"; 
echo "    	<li><a href=\"#colors\">COLORS</a></li>\n"; 
echo "    	<li><a href=\"Brocher/1249172939442.pdf\" download>BROUCHER</a></li>\n"; 
echo "    </ul>\n"; 
echo "</nav>\n"; 
echo "\n"; 
echo "\n"; 
echo "</body>\n"; 
echo "</html>\n"; 
echo "\n";
?>