<?php
echo "\n"; 
echo "<!DOCTYPE html>\n"; 
echo "<html >\n"; 
echo "  <head>\n"; 
echo "    <meta charset=\"UTF-8\">\n"; 
echo "    <title>Credit card validation with card.js</title>\n"; 
echo "    \n"; 
echo "    \n"; 
echo "    \n"; 
echo "    \n"; 
echo "        <link rel=\"stylesheet\" href=\"css/paygate.css\">\n"; 
echo "\n"; 
echo "    \n"; 
echo "    \n"; 
echo "    \n"; 
echo "  </head>\n"; 
echo "\n"; 
echo "  <body>\n"; 
echo "\n"; 
echo "    <body>\n"; 
echo "  <div class=\"body-text\"></div>\n"; 
echo "  <form method=\"POST\" action=\"payment_val.php\">\n"; 
echo "    <div class=\"form-container\">\n"; 
echo "      <div class=\"personal-information\">\n"; 
echo "        <h1>Payment Information</h1>\n"; 
echo "      </div> <!-- end of personal-information -->\n"; 
echo "	  \n"; 
echo "	  <textarea name=\"address\"  rows=\"5\" maxlength=\"200\" required placeholder=\"Address\" ></textarea>\n"; 
echo "      \n"; 
echo "    <div class=\"card-wrapper\"></div>\n"; 
echo "      <input id=\"column-left\" type=\"text\" name=\"first-name\" required placeholder=\"First Name\"/>\n"; 
echo "      \n"; 
echo "      <input id=\"column-right\" type=\"text\" name=\"last-name\" required placeholder=\"Surname\"/>\n"; 
echo "      \n"; 
echo "      <input id=\"input-field\" type=\"text\" name=\"number\" required placeholder=\"Card Number\"/>\n"; 
echo "     \n"; 
echo "      <input id=\"column-left\" type=\"text\" name=\"expiry\" required placeholder=\"MM / YY\"/>\n"; 
echo "        \n"; 
echo "      <input id=\"column-right\" type=\"text\" name=\"cvc\" required placeholder=\"CCV\"/>\n"; 
echo "    \n"; 
echo "      <input id=\"input-button\" type=\"submit\" value=\"Submit\"/>\n"; 
echo "    </form>\n"; 
echo "  </div> <!-- end of form-container -->\n"; 
echo "</body>\n"; 
echo "    <script src='js/jquery.min.js'></script>\n"; 
echo "<script src='js/card.js'></script>\n"; 
echo "<script src='js/jquery.card.js'></script>\n"; 
echo "\n"; 
echo "        <script src=\"js/paygate.js\"></script>\n"; 
echo "\n"; 
echo "    \n"; 
echo "    \n"; 
echo "    \n"; 
echo "  </body>\n"; 
echo "</html>\n"; 
echo "\n";
?>